default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: expense_tracker_development

test:
  <<: *default
  database: expense_tracker_test

production:
  <<: *default
  database: expense_tracker_production
  username: expense
  password: <%= ENV['EXPENSE_TRACKER_DATABASE_PASSWORD'] %>
